export { default as Product } from './product/index';
export { default as Home } from './Home';
export { default as Solution } from './solution/index';
export { default as Login } from './login/index';
export { default as SignUp } from './signup/index';
export { default as Support } from './support/index';
export { default as Sponsor } from './sponsor/index';
export { default as EventProfile } from './dashboard/index';
export { default as EditEvent  } from './dashboard/edit';
